# Generated by Django 5.0.2 on 2024-03-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customer_alter_order_performer'),
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
