# Generated by Django 5.0.2 on 2024-02-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
