# Generated by Django 5.0.2 on 2024-02-12 15:02

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
