# Generated by Django 5.0.2 on 2024-02-10 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заказы')),
                ('descriptiom', models.TextField(verbose_name='Описание')),
                ('price', models.TextField(verbose_name='Цена')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customer', to='users.user', verbose_name='Заказчик')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_performer', to='users.user', verbose_name='Исполнитель')),
            ],
        ),
    ]
